In [3]:
import pandas as pd

In [11]:
pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

In [ ]:
df = pd.read_csv("../results/modified_files_2024.csv")

In [6]:
df.sample(5)

,origin,revision,branch,snapshot_without,path,status
7654872,https://github.com/saltstack/salt,swh:1:rev:723b278bfaab46e9df0e6d9b28782c745d15...,refs/pull/63401/head,swh:1:snp:1feeff02b7f97ea80e0308b21ad80b93c314...,./doc/topics/releases/0.13.0.rst,Modified
15479162,https://github.com/dagster-io/dagster,swh:1:rev:3f69c803c1f441e14e99ed86190a04ff8353...,refs/pull/14711/head,swh:1:snp:dfefd9db1523048fa6e746a2750974d201d1...,./js_modules/dagit/packages/core/src/graph/opt...,NotFound
5950990,https://github.com/django/django,swh:1:rev:cabbe1c3f56d5a1e3ea2a98da3d53d34acfb...,refs/pull/11452/head,swh:1:snp:86134df6204ea9dd1b82262c1fa3fc341c31...,./django/contrib/postgres/locale/be/LC_MESSAGE...,Modified
13016874,https://github.com/getsentry/sentry,swh:1:rev:ed0dba68637e033aa2f4a4fd8fbacb2c134e...,refs/heads/sharky/perf-issue-data-to-issue-pla...,swh:1:snp:27656227bdca913457e01b4f1d6b305ae87c...,./tests/sentry/incidents/action_handlers/test_...,Modified
10307117,https://github.com/home-assistant/core,swh:1:rev:ca7a77fd4d38d948b8bd51a0ab01f0b786f1...,refs/pull/115128/head,swh:1:snp:3fcf277af4396178fecd81325950dda017bd...,./tests/components/google_assistant/test_diagn...,Modified

In [12]:
df.loc[df['path'].str.contains("license", case=False) & df['branch'].str.contains("main", case=False)]

,origin,revision,branch,snapshot_without,path,status
1353561,https://github.com/Chia-Network/chia-blockchain,swh:1:rev:9545dc13647ec3a15e4b2638810360ee84289b48,refs/heads/dependabot-pip-main-setproctitle-1.3.2,swh:1:snp:9562e1fc24eb7175397112a82149fcbdcdeb37e8,./LICENSE,Modified
9955118,https://github.com/getsentry/sentry,swh:1:rev:81855b0585f9c40b7d9cba6b238cd9b6ae175116,refs/heads/dlee/scopes-main,swh:1:snp:d566a0d1136d60afff2829615c5b08aab436e0ed,./.github/workflows/enforce-license-compliance.yml,Modified
14905506,https://github.com/getsentry/sentry,swh:1:rev:f83b39409accb1c1f9b5a341004f8c9bbb351519,refs/heads/hybrid-cloud/fix-customer-domain-middleware-no-redirect-for-non-GET,swh:1:snp:013e038829111c0d214ee6f2b93c31766f57db3a,./LICENSE,Modified