In [2]:
import pickle
import pandas as pd
pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows', None
pd.set_option('display.max_colwidth', None)

In [4]:
df = pd.read_csv("../defaultNix.csv")

In [8]:
df['origin'].value_counts()

origin
https://github.com/r-ryantm/nixpkgs            6806320
https://github.com/NixOS/nixpkgs                912801
https://gitlab.com/Moredread/nixpkgs.git        268062
https://github.com/bb2020/nixpkgs               229104
https://github.com/Izorkin/nixpkgs              203311
                                                ...
https://github.com/giuseppe/skopeo                   1
https://github.com/Roonas/machine-config             1
https://github.com/ggonthier/math-comp               1
https://github.com/mpickering/eventlog2html          1
https://github.com/dpwiz/autoapply                   1
Name: count, Length: 1594, dtype: int64

In [9]:
modified = df[df['status'] == "Modified"]
removed = df[df['status'] == "NotFound"]
print(f'modified: {len(modified):,}')
print(f'removed: {len(removed):,}')

modified: 12,748,662
removed: 653,274

In [10]:
modified['origin'].value_counts()

origin
https://github.com/r-ryantm/nixpkgs            6533186
https://github.com/NixOS/nixpkgs                868478
https://gitlab.com/Moredread/nixpkgs.git        255916
https://github.com/bb2020/nixpkgs               217681
https://github.com/Izorkin/nixpkgs              195420
                                                ...
https://github.com/davidak/nix                       1
https://github.com/giuseppe/libpod                   1
https://github.com/eugeneia/raptorjit                1
https://github.com/LumiGuide/haskell-opencv          1
https://github.com/paddygord/lang                    1
Name: count, Length: 1433, dtype: int64

In [11]:
removed['origin'].value_counts()

origin
https://github.com/r-ryantm/nixpkgs           273134
https://github.com/NixOS/nixpkgs               44323
https://github.com/phunehehe/docker-images     35989
https://github.com/ccce/nixpkgs                12317
https://gitlab.com/Moredread/nixpkgs.git       12146
                                               ...
https://github.com/berquist/dotfiles               1
https://github.com/dpausp/ekklesia-portal          1
https://github.com/nbraud/memtree                  1
https://github.com/layus/vuizvui                   1
https://github.com/openebs/Mayastor                1
Name: count, Length: 741, dtype: int64

In [6]:
sample = df.sample(10).copy()

In [7]:
sample

,origin,snapshot_src,branch_name,missing_commit,snapshot_dst,first_difference,main_category,sub_categories,stars,normalized_branch
346687,https://github.com/CrowdStrike/monorepo-next,swh:1:snp:606490e2191acf75cbdba5194abf2e6fad9de0ed,refs/pull/316/head,swh:1:rev:c0e8af2531b0d44c3b9750c03050e0b658100e7d,swh:1:snp:1e548eb02bc4e3796fa06e47ed24d9a43f336507,NaN,DIR,FileModified,10.0,refs/pull/{x}/head
348049,https://github.com/dmvk/flink,swh:1:snp:87949a0f784a6a449451b81015a68a3100336736,refs/heads/FLINK-31996,swh:1:rev:8c07ee4ee759fe351480649f43a359bf0881e4c9,swh:1:snp:982f4a26a2d02c20ae10b1553c8e85657c91af2b,NaN,DIR,FileModified,0.0,refs/heads/FLINK-31996
65659,https://github.com/bnjbvr/kresus,swh:1:snp:c479c454b6879518574841c86eab7e6b516ec363,refs/merge-requests/496/head,swh:1:rev:33d32bc7ac2513d550e1f8aabb81958aaac2450a,swh:1:snp:f8353f2a3946783a593a5dc08be419bc87c25a01,swh:1:rev:33d32bc7ac2513d550e1f8aabb81958aaac2450a,DIR,DifferentBranchName,Unknown,refs/merge-requests/496/head
65306,https://gitlab.com/Hacker1245/pmaports.git,swh:1:snp:d3f2352d27fe973ada2473009a248fc16c31ef7c,refs/heads/use-binutils-cross-from-alpine,swh:1:rev:e315d2bdacdf93ac181ed163e0d53dfb1fb161b1,swh:1:snp:00a7cc3d3611b1d1a4cdca3261c8e5f1e897f893,NaN,DIR,FileModified,Unknown,refs/heads/use-binutils-cross-from-alpine
352889,https://gitlab.com/krr/IDP-Z3.git,swh:1:snp:ea9d7f829c2639bac5b68b028d495d6c8a5ca6e3,refs/merge-requests/116/merge,swh:1:rev:5602815287ac238fe09282daa62c1f55c8fd107b,swh:1:snp:18a63ac3773f09d8c9895d892d4f74301f54e51f,NaN,DIR,FileModified FileRemoved,Unknown,refs/merge-requests/116/merge
154354,https://gitlab.com/Spixmaster/tools-cpp.git,swh:1:snp:e93a51d727932495bbb94739e122c0bb0d8a4321,refs/tags/v3.0.3,swh:1:rev:c727feb60e97872fb86041eb309bf3af4bb5b0e6,swh:1:snp:bbf8e2319756dd138c8499c523d312f1552fcfd2,NaN,DIR,FileModified FileRemoved,Unknown,refs/tags/v3.0.3
5123,https://github.com/molguin92/configs,swh:1:snp:a5a8c9f5a613eaa218a4a1de722a00944651d9df,refs/heads/master,swh:1:rev:3e3aeb8238f8f7ef1f89c9639f97a3466d89b69d,swh:1:snp:beedb4fbeebb14ef78ff48679d5d8a0370c742a3,NaN,DIR,FileRemoved,Unknown,"refs/heads/{master,main}"
364647,https://github.com/uzh-bf/klicker-uzh,swh:1:snp:65fe63e75c7ac04f85ff58521d4b9a580e7c7afb,refs/pull/201/head,swh:1:rev:4b6471bc5505fcdeea839640d3eefb099704d0cf,swh:1:snp:4f6512a4ba5aa250058aec50099e734a9fd55510,swh:1:dir:9768eece2f856b34a11d07b5384f2b42a50c7159,META,Message Author Date CommitterDate Committer,40.0,refs/pull/{x}/head
102717,https://github.com/tkashkin/GameHub,swh:1:snp:17bbd404055694fb56433b0c7611c5e8a38e1c83,refs/tags/0.5.6,swh:1:rev:cd32d22ca120fe8921b253ce3ebec91dfcd975a2,swh:1:snp:e036e58887220255c4f3cbcfed3c4885052528af,swh:1:rev:cd32d22ca120fe8921b253ce3ebec91dfcd975a2,DIR,DifferentBranchName,2445.0,refs/tags/0.5.6
155226,https://github.com/DashboardHub/PipelineDashboard,swh:1:snp:ba924fbac06031e45f68fd39f128a0ec73ad6e90,refs/heads/v0.10-alpha,swh:1:rev:b7d4c9b8b7acea4eeabed1ead3e9f51dd987437d,swh:1:snp:c7536e911301f05c4b3aab347958d5815c63acbe,swh:1:rev:b7d4c9b8b7acea4eeabed1ead3e9f51dd987437d,DIR,DifferentBranchName,152.0,refs/heads/v0.10-alpha

In [8]:
sample.to_csv("/home/infres/rapaport/git-historian/dataset-teaser/teaser_altered_histories.csv", sep=';', index=False)

In [9]:
origins = sample['origin'].drop_duplicates().reset_index(drop=True)

In [10]:
origins_df = origins.to_frame(name='origin')

In [11]:
import duckdb
import time

In [12]:
result = duckdb.sql("""
    SELECT origin FROM origins_df
""").fetchdf()
result

                                              origin
0       https://github.com/CrowdStrike/monorepo-next
1                      https://github.com/dmvk/flink
2                   https://github.com/bnjbvr/kresus
3         https://gitlab.com/Hacker1245/pmaports.git
4                  https://gitlab.com/krr/IDP-Z3.git
5        https://gitlab.com/Spixmaster/tools-cpp.git
6               https://github.com/molguin92/configs
7              https://github.com/uzh-bf/klicker-uzh
8                https://github.com/tkashkin/GameHub
9  https://github.com/DashboardHub/PipelineDashboard

In [13]:
start = time.time()
result = duckdb.sql("""
    SELECT *
    FROM read_csv_auto('../results/modified_files.csv', strict_mode=false, max_line_size=10000000, ignore_errors=true)
    WHERE origin IN (SELECT origin FROM origins_df)
""").fetchdf()
print("exec time: ", time.time() - start)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

exec time:  943.6398797035217

In [14]:
result.to_csv("/home/infres/rapaport/git-historian/dataset-teaser/teaser_modified_files.csv", sep=';', index=False)

In [15]:
with open("../results/teaser_modified_files.pkl", 'wb') as f:
    pickle.dump(result, f)

In [16]:
result

,origin,revision,branch,snapshot_without,path,status
0,https://github.com/dmvk/flink,swh:1:rev:1e4d3186bbefcceabac4ac27b2eede5891545e54,refs/heads/FLINK-24543-113,swh:1:snp:77b270e1f298711561d8ae5c20c8ce9c95a0118d,./flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/rules/logical/ConvertToNotInOrInRule.scala,Modified
1,https://github.com/dmvk/flink,swh:1:rev:1e4d3186bbefcceabac4ac27b2eede5891545e54,refs/heads/FLINK-24543-113,swh:1:snp:77b270e1f298711561d8ae5c20c8ce9c95a0118d,./flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/BufferTimeoutITCase.java,Modified
2,https://github.com/dmvk/flink,swh:1:rev:1e4d3186bbefcceabac4ac27b2eede5891545e54,refs/heads/FLINK-24543-113,swh:1:snp:77b270e1f298711561d8ae5c20c8ce9c95a0118d,./flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequest.java,Modified
3,https://github.com/dmvk/flink,swh:1:rev:1e4d3186bbefcceabac4ac27b2eede5891545e54,refs/heads/FLINK-24543-113,swh:1:snp:77b270e1f298711561d8ae5c20c8ce9c95a0118d,./flink-end-to-end-tests/test-scripts/common_ssl.sh,Modified
4,https://github.com/dmvk/flink,swh:1:rev:1e4d3186bbefcceabac4ac27b2eede5891545e54,refs/heads/FLINK-24543-113,swh:1:snp:77b270e1f298711561d8ae5c20c8ce9c95a0118d,./flink-connectors/flink-connector-files/src/test/resources/bucket-state-migration-test/full-v2-template/bucket/test-bucket/.part-0-0.inprogress.9731063e-2b28-4701-8cc1-e706480b8022,NotFound
...,...,...,...,...,...,...
85663,https://github.com/uzh-bf/klicker-uzh,swh:1:rev:e22f8d5c205af333b89449dfb0d2602286eddd86,refs/heads/dependabot/npm_and_yarn/apps/frontend-pwa/v2/apollo/client-3.7.1,swh:1:snp:835bcd2d1778581b4889918c9b731c82e7539c86,./apps/frontend-manage/src/pages/sessions/[id]/evaluation.tsx,Modified
85664,https://github.com/uzh-bf/klicker-uzh,swh:1:rev:e22f8d5c205af333b89449dfb0d2602286eddd86,refs/heads/dependabot/npm_and_yarn/apps/frontend-pwa/v2/apollo/client-3.7.1,swh:1:snp:835bcd2d1778581b4889918c9b731c82e7539c86,./package-lock.json,Modified
85665,https://github.com/uzh-bf/klicker-uzh,swh:1:rev:e22f8d5c205af333b89449dfb0d2602286eddd86,refs/heads/dependabot/npm_and_yarn/apps/frontend-pwa/v2/apollo/client-3.7.1,swh:1:snp:835bcd2d1778581b4889918c9b731c82e7539c86,./apps/frontend-manage/src/components/questions/QuestionPreviewModal.tsx,Modified
85666,https://github.com/uzh-bf/klicker-uzh,swh:1:rev:e22f8d5c205af333b89449dfb0d2602286eddd86,refs/heads/dependabot/npm_and_yarn/apps/frontend-pwa/v2/apollo/client-3.7.1,swh:1:snp:835bcd2d1778581b4889918c9b731c82e7539c86,./CHANGELOG.md,Modified
85667,https://github.com/uzh-bf/klicker-uzh,swh:1:rev:e22f8d5c205af333b89449dfb0d2602286eddd86,refs/heads/dependabot/npm_and_yarn/apps/frontend-pwa/v2/apollo/client-3.7.1,swh:1:snp:835bcd2d1778581b4889918c9b731c82e7539c86,./packages/grading/package.json,Modified

In [5]:
df_b.head(20)

        file_name                 branch    count
0      index.html      refs/heads/master  1909472
1      index.html    refs/heads/gh-pages  1424082
2       meta.yaml        refs/heads/bulk  1221710
3        Makefile      refs/heads/master  1013563
4       README.md      refs/heads/master   986693
5        Manifest      refs/heads/master   927861
6      index.d.ts      refs/heads/master   896104
7    package.json      refs/heads/master   775494
8     tslint.json      refs/heads/master   763951
9   tsconfig.json      refs/heads/master   739173
10       Makefile  refs/heads/linux-next   683706
11       index.js      refs/heads/master   656075
12   metadata.xml      refs/heads/master   623635
13    default.nix      refs/heads/master   607070
14       Manifest      refs/heads/emerge   591378
15     index.html                   HEAD   584199
16        Kconfig  refs/heads/linux-next   540285
17        LICENSE      refs/heads/master   460744
18      meta.yaml      refs/heads/master   409995
19      README.md                   HEAD   384976

In [6]:
df.head(20)

         file_name     count
0      default.nix  13401935
1     package.json  12594717
2         Makefile  10615195
3        README.md   9969599
4         index.js   9129894
5         Manifest   8891876
6          pom.xml   7080355
7       index.html   6297643
8        meta.yaml   5425074
9         index.md   5372929
10    CHANGELOG.md   5001971
11     __init__.py   4859517
12    metadata.xml   4477947
13  CMakeLists.txt   4380963
14      package.py   4336900
15        APKBUILD   3375064
16        template   3122049
17           BUILD   3018131
18        index.ts   2764520
19         LICENSE   2762147

In [5]:
df.loc[df['file_name'] == "id_rsa"]

       file_name  count
325169    id_rsa    759

In [6]:
df.loc[df["file_name"].apply(lambda x: "licence" in x or "license" in x)]

                                    file_name   count
106                                   license  406103
797                                license.md   60054
1119                               license.rb   46078
1291                              license.txt   40430
2120                          license_spec.rb   27099
...                                       ...     ...
44119984  iscroll-license.764d9c6b8603.txt.gz       1
44119989               iscroll-license.txt.gz       1
44122044    edit-license-bulk-edit-export.png       1
44127042                 encoding-license.txt       1
44131664             license-riverock-webmill       1

[17991 rows x 2 columns]

In [8]:
total_count_license = df.loc[df["file_name"].apply(lambda x: "licence" in x or "license" in x)]['count'].sum()
print(f"Total count across all license files: {total_count_license:,}")

Total count across all license files: 1,934,834